[build]
builder = "DOCKERFILE"
buildCommand = "npm run build"

[deploy]
startCommand = "npm run start:proxy"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
PORT = { default = "3001" }

[[services]]
name = "shopify-processor" 